import { describe, it, expect } from 'vitest';
import { detectScaffold, normalise, parseHead } from './scaffold';

const at = (host: string) => new URL(`https://${host}/`);
const page = (html: string, host = 'myapp.com') => ({
  html,
  status: 200,
  contentType: 'text/html; charset=utf-8',
  url: at(host),
});

const NEXT_DEFAULT = `<head><title>Create Next App</title><meta name="description" content="Generated by create next app"/></head>`;
const VITE_DEFAULT = `<head><link rel="icon" type="image/svg+xml" href="/vite.svg" /><title>Vite + React + TS</title></head>`;

describe('normalise', () => {
  it('decodes entities, collapses whitespace and trims', () => {
    expect(normalise('  Create&nbsp;Next   App ')).toBe('Create Next App');
    expect(normalise('Template: Vite + React + TS ')).toBe('Template: Vite + React + TS');
    expect(normalise('&amp; &lt; &#39;')).toBe("& < '");
  });

  it('never strips emoji — it is the only field identifying one vendor', () => {
    expect(normalise('⚡️ Bolt.new + Vite + React')).toBe('⚡️ Bolt.new + Vite + React');
  });
});

describe('exact matching, never substring', () => {
  it('flags the untouched create-next-app head', () => {
    const r = detectScaffold(page(NEXT_DEFAULT));
    expect(r.verdict).toBe('default-metadata');
    expect(r.finding?.generator).toBe('create-next-app');
    expect(r.finding?.severity).toBe('warning');
  });

  it('does NOT flag a page whose title merely contains the phrase', () => {
    // A tutorial or blog post is the obvious victim of substring matching.
    const r = detectScaffold(page('<title>How I used Create Next App to ship in a day</title>'));
    expect(r.verdict).toBe('clean');
  });

  it('does NOT flag a title that only prefixes the default', () => {
    // Confirmed live: a real negative target serves this exact shape.
    const r = detectScaffold(page('<head><title>Template: Vite + React + TS </title></head>'));
    expect(r.verdict).toBe('clean');
  });

  it('needs BOTH fields for create-next-app, not just the title', () => {
    // next.vercel.app ships the default title with no description.
    expect(detectScaffold(page('<title>Create Next App</title>')).verdict).toBe('clean');
  });
});

describe('create-vite', () => {
  it('flags the current scaffold: title + svg icon + NO description', () => {
    const r = detectScaffold(page(VITE_DEFAULT));
    expect(r.finding?.generator).toBe('create-vite');
  });

  it('covers the -ts variants an earlier draft wrongly claimed do not exist', () => {
    for (const t of ['Vite + Preact + TS', 'Vite + Solid + TS', 'Vite + Lit + TS', 'Vite + Qwik + TS']) {
      const html = `<link rel="icon" type="image/svg+xml" href="/favicon.svg" /><title>${t}</title>`;
      expect(detectScaffold(page(html)).verdict).toBe('default-metadata');
    }
  });

  it('declines once the author has written a description', () => {
    const html = `${VITE_DEFAULT}<meta name="description" content="My actual app">`;
    expect(detectScaffold(page(html)).verdict).toBe('clean');
  });

  it('catches legacy v2 without asserting the icon path', () => {
    // v2 kept the icon under /src/, so the build hashes and rewrites it.
    const html = '<link rel="icon" type="image/svg+xml" href="/assets/favicon.17e50649.svg" /><title>Vite App</title>';
    const r = detectScaffold(page(html));
    expect(r.finding?.generator).toBe('create-vite (legacy)');
  });
});

describe('vendor attribution is never guessed from a generic string', () => {
  it('calls a stock Vite head create-vite, NOT the AI tool that emitted it', () => {
    // Bolt publishes starter templates shipping stock create-vite heads, so
    // this string proves the scaffold and nothing about the vendor.
    expect(detectScaffold(page(VITE_DEFAULT)).finding?.generator).toBe('create-vite');
  });

  it('names Lovable only on its own author meta', () => {
    const html = '<title>My App</title><meta name="description" content="Lovable Generated Project"><meta name="author" content="Lovable">';
    expect(detectScaffold(page(html)).finding?.generator).toBe('Lovable');
    // Description alone is not enough to name them.
    const partial = '<title>My App</title><meta name="description" content="Lovable Generated Project">';
    expect(detectScaffold(page(partial)).verdict).toBe('clean');
  });

  it('flags Bolt on its emoji title and says the evidence is a single field', () => {
    const r = detectScaffold(page('<title>⚡️ Bolt.new + Vite + React</title>'));
    expect(r.finding?.generator).toBe('Bolt.new');
    expect(r.finding?.fields[0]).toMatch(/single field/);
  });

  it('never flags the bare Astro title, only "Astro Basics" with the generator meta', () => {
    expect(detectScaffold(page('<title>Astro</title><meta name="generator" content="Astro v5.18.2">')).verdict).toBe('clean');
    const r = detectScaffold(page('<title>Astro Basics</title><meta name="generator" content="Astro v5.18.2">'));
    expect(r.finding?.generator).toBe('Astro');
  });

  it('uses only the description for SvelteKit — its demo title is "Home"', () => {
    expect(detectScaffold(page('<title>Home</title>')).verdict).toBe('clean');
    expect(detectScaffold(page('<title>Home</title><meta name="description" content="Svelte demo app">')).finding?.generator).toBe('SvelteKit');
  });
});

describe('the false-positive class: published template demos', () => {
  it('downgrades to informational on a host that calls itself a template', () => {
    // Vercel's own nextjs-fastapi-starter serves both default fields and is
    // supposed to. Provenance is not knowable from outside, so we soften the
    // claim rather than accuse.
    const r = detectScaffold({ ...page(NEXT_DEFAULT), url: at('nextjs-fastapi-starter.vercel.app') });
    expect(r.verdict).toBe('default-metadata');
    expect(r.finding?.severity).toBe('info');
    expect(r.reason).toMatch(/published .* template/);
  });

  it('keeps full severity on an ordinary custom domain', () => {
    const r = detectScaffold({ ...page(NEXT_DEFAULT), url: at('acme-invoices.com') });
    expect(r.finding?.severity).toBe('warning');
  });

  it('only softens on preview hosts, not any domain containing the word', () => {
    const r = detectScaffold({ ...page(NEXT_DEFAULT), url: at('demolition-co.com') });
    expect(r.finding?.severity).toBe('warning');
  });
});

describe('unknown, never a pass', () => {
  it('when the head is written by JavaScript there is no title to judge', () => {
    const r = detectScaffold(page('<html><body><div id="root"></div></body></html>'));
    expect(r.verdict).toBe('unknown');
    expect(r.reason).toMatch(/sets its title in the browser/);
  });

  it('when a challenge or login page was served', () => {
    expect(detectScaffold(page('<title>Just a moment...</title>')).verdict).toBe('unknown');
    expect(detectScaffold(page('<title>x</title>_vercel/sso')).verdict).toBe('unknown');
  });

  it('when the response is not 200 HTML', () => {
    expect(detectScaffold({ ...page(NEXT_DEFAULT), status: 403 }).verdict).toBe('unknown');
    expect(detectScaffold({ ...page(NEXT_DEFAULT), contentType: 'application/json' }).verdict).toBe('unknown');
  });
});

describe('parseHead', () => {
  it('reads title, metas and the svg icon', () => {
    const h = parseHead('<title> A </title><meta name="Description" content="d"><link rel="icon" type="image/svg+xml" href="/x.svg">');
    expect(h.title).toBe('A');
    expect(h.meta.description).toBe('d');
    expect(h.svgIconHref).toBe('/x.svg');
  });
});
