/**
 * Scaffold default metadata still being served.
 *
 * `<title>Create Next App</title>` is not a missing title — every existing
 * audit sees a title and ticks the box. It is a WRONG title, and it is what
 * Google, ChatGPT and every link unfurler are told the app is called. That gap
 * between "present" and "correct" is why nobody else reports it.
 *
 * ── Why this check is so conservative ──────────────────────────────────────
 * Adversarial verification found a real, populated false-positive class:
 * OFFICIAL TEMPLATE DEMOS. Vercel's own published nextjs-fastapi-starter serves
 * both `Create Next App` and `Generated by create next app`, and it is supposed
 * to. So do "Deploy to Vercel" button demos, tutorial repos and gallery entries
 * — exactly the population a scanner trips over. Two matching fields do not
 * distinguish a forgotten default from a deliberate template.
 *
 * We cannot determine provenance from the outside, so we do the next honest
 * thing: flag it, but downgrade to informational on hosts whose name says
 * template/starter/demo, and word the finding as an observation about the
 * served HTML rather than an accusation.
 *
 * ── And never name a vendor off a generic string ───────────────────────────
 * Bolt publishes starter templates that ship stock create-vite and
 * create-next-app heads. So `Vite + React + TS` proves create-vite and nothing
 * else; it never proves Bolt. Only a vendor's own distinctive fields (Lovable's
 * author meta, v0's title+description pair, Bolt's emoji title) name a vendor.
 *
 * Every constant below was re-retrieved from the generator's own template in
 * source control on 2026-08-20.
 */

export interface ScaffoldFinding {
  /** The generator whose default this is — never inferred beyond the evidence. */
  generator: string;
  /** Exactly which fields matched, quoted, so the finding shows its work. */
  fields: string[];
  /**
   * `info` when the host looks like a template demo, where shipping the default
   * is the correct behaviour rather than an oversight.
   */
  severity: 'warning' | 'info';
}

export interface ScaffoldResult {
  verdict: 'default-metadata' | 'clean' | 'unknown';
  finding: ScaffoldFinding | null;
  reason: string;
}

/** Decode the entities that realistically appear in a title or meta content. */
function decodeEntities(s: string): string {
  return s
    .replace(/&(#\d+|#x[0-9a-f]+|amp|lt|gt|quot|apos|nbsp);/gi, (whole, body: string) => {
      const b = body.toLowerCase();
      if (b === 'amp') return '&';
      if (b === 'lt') return '<';
      if (b === 'gt') return '>';
      if (b === 'quot') return '"';
      if (b === 'apos') return "'";
      if (b === 'nbsp') return ' ';
      const cp = b.startsWith('#x') ? parseInt(b.slice(2), 16) : parseInt(b.slice(1), 10);
      return Number.isFinite(cp) ? String.fromCodePoint(cp) : whole;
    });
}

/**
 * Decode, normalise to NFC, collapse whitespace runs, trim.
 *
 * Comparison is then EXACT and case-sensitive — never substring. A blog post
 * titled "How I used Create Next App" must not match, and emoji must survive
 * intact: Bolt's default title carries U+FE0F and stripping it would break the
 * only field that identifies it.
 */
export function normalise(s: string | undefined): string {
  if (s === undefined) return '';
  return decodeEntities(s).normalize('NFC').replace(/\s+/g, ' ').trim();
}

interface Head {
  title?: string;
  meta: Record<string, string>;
  /** href of link[rel=icon][type="image/svg+xml"], if any. */
  svgIconHref?: string;
  hasSvgIcon: boolean;
  hasTitleElement: boolean;
  html: string;
}

function attr(tag: string, name: string): string | undefined {
  const m = tag.match(new RegExp(`\\b${name}\\s*=\\s*("([^"]*)"|'([^']*)'|([^\\s>]+))`, 'i'));
  return m ? (m[2] ?? m[3] ?? m[4]) : undefined;
}

export function parseHead(html: string): Head {
  const titleMatch = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  const meta: Record<string, string> = {};
  for (const m of html.matchAll(/<meta\b[^>]*>/gi)) {
    const tag = m[0];
    const name = attr(tag, 'name');
    const content = attr(tag, 'content');
    if (name && content !== undefined) meta[name.toLowerCase()] = content;
  }
  let svgIconHref: string | undefined;
  let hasSvgIcon = false;
  for (const m of html.matchAll(/<link\b[^>]*>/gi)) {
    const tag = m[0];
    const rel = (attr(tag, 'rel') ?? '').toLowerCase();
    if (!/\bicon\b/.test(rel)) continue;
    if ((attr(tag, 'type') ?? '').toLowerCase() === 'image/svg+xml') {
      hasSvgIcon = true;
      svgIconHref ??= attr(tag, 'href');
    }
  }
  return {
    title: titleMatch ? normalise(titleMatch[1]) : undefined,
    meta,
    svgIconHref,
    hasSvgIcon,
    hasTitleElement: !!titleMatch,
    html,
  };
}

/** The 16 current create-vite titles, each fetched from its own template. */
const VITE_TITLES = new Set([
  'Vite + JS', 'Vite + TS',
  'Vite + React', 'Vite + React + TS',
  'Vite + Vue', 'Vite + Vue + TS',
  'Vite + Svelte', 'Vite + Svelte + TS',
  'Vite + Preact', 'Vite + Preact + TS',
  'Vite + Solid', 'Vite + Solid + TS',
  'Vite + Lit', 'Vite + Lit + TS',
  'Vite + Qwik', 'Vite + Qwik + TS',
]);
/** v3-v8 shipped /vite.svg; current main ships /favicon.svg. */
const VITE_ICONS = new Set(['/vite.svg', '/favicon.svg']);

/** Responses that are an interstitial rather than the app. */
const INTERSTITIAL = /Just a moment\.\.\.|Checking your browser|cf-browser-verification|challenges\.cloudflare\.com|_vercel\/sso|Authentication Required/i;

/** Hostnames that advertise themselves as templates — downgrade, don't accuse. */
const TEMPLATE_HOST = /(^|[.-])(template|starter|boilerplate|example|demo|playground)([.-]|$)/i;
const PREVIEW_HOST = /\.(vercel\.app|netlify\.app|pages\.dev)$/i;

type Rule = (h: Head) => { generator: string; fields: string[] } | null;

/**
 * Each rule is the exact conjunction verified against the generator's template.
 * Order matters only for readability — at most one realistically matches.
 */
const RULES: Rule[] = [
  // create-next-app. Title AND description, because either alone is common.
  (h) =>
    h.title === 'Create Next App' && normalise(h.meta.description) === 'Generated by create next app'
      ? { generator: 'create-next-app', fields: ['<title>Create Next App</title>', 'description "Generated by create next app"'] }
      : null,

  // create-react-app. The description is the trigger; the title corroborates.
  (h) =>
    normalise(h.meta.description) === 'Web site created using create-react-app' && h.title === 'React App'
      ? { generator: 'create-react-app', fields: ['<title>React App</title>', 'description "Web site created using create-react-app"'] }
      : null,

  // create-vite v3+. The scaffold ships no description at all, which is itself
  // part of the fingerprint.
  (h) =>
    h.title !== undefined &&
    VITE_TITLES.has(h.title) &&
    h.svgIconHref !== undefined &&
    VITE_ICONS.has(h.svgIconHref) &&
    h.meta.description === undefined
      ? { generator: 'create-vite', fields: [`<title>${h.title}</title>`, `svg icon ${h.svgIconHref}`, 'no meta description'] }
      : null,

  // create-vite v2. The icon lived under /src/ so the build hashes and rewrites
  // it — assert only that an svg icon exists, never its path.
  (h) =>
    h.title === 'Vite App' && h.meta.description === undefined && h.hasSvgIcon
      ? { generator: 'create-vite (legacy)', fields: ['<title>Vite App</title>', 'no meta description'] }
      : null,

  // Astro. Never flag the bare title "Astro" — too generic.
  (h) =>
    h.title === 'Astro Basics' && (h.meta.generator ?? '').startsWith('Astro v')
      ? { generator: 'Astro', fields: ['<title>Astro Basics</title>', `generator "${h.meta.generator}"`] }
      : null,

  // SvelteKit. Description only — the demo title is "Home", far too common.
  (h) =>
    normalise(h.meta.description) === 'Svelte demo app'
      ? { generator: 'SvelteKit', fields: ['description "Svelte demo app"'] }
      : null,

  (h) =>
    h.title === 'Welcome to Nuxt!' && h.html.includes('id="__nuxt"') && h.html.includes('https://nuxt.com?utm_source=nuxt-welcome')
      ? { generator: 'Nuxt', fields: ['<title>Welcome to Nuxt!</title>', 'the untouched Nuxt welcome page'] }
      : null,

  (h) =>
    normalise(h.meta.description) === 'Lovable Generated Project' && normalise(h.meta.author) === 'Lovable'
      ? { generator: 'Lovable', fields: ['description "Lovable Generated Project"', 'author "Lovable"'] }
      : null,

  (h) =>
    h.title === 'v0 App' && normalise(h.meta.description) === 'Created with v0'
      ? { generator: 'v0', fields: ['<title>v0 App</title>', 'description "Created with v0"'] }
      : null,

  // Bolt. Single-field, and said so honestly in the evidence.
  (h) =>
    h.title === '⚡️ Bolt.new + Vite + React'
      ? { generator: 'Bolt.new', fields: ['<title>⚡️ Bolt.new + Vite + React</title> (single field)'] }
      : null,
];

export function detectScaffold(input: { html: string; status: number; contentType: string; url: URL }): ScaffoldResult {
  if (input.status !== 200 || !/text\/html/i.test(input.contentType)) {
    return { verdict: 'unknown', finding: null, reason: 'the page did not return HTML, so we could not read its title' };
  }
  if (INTERSTITIAL.test(input.html)) {
    return { verdict: 'unknown', finding: null, reason: 'a challenge or login page was served instead of the app' };
  }

  const head = parseHead(input.html);
  if (!head.hasTitleElement) {
    // react.dev behaves this way. Absence is never evidence of a default.
    return {
      verdict: 'unknown',
      finding: null,
      reason: 'this page sets its title in the browser, so the served HTML has none for us to check',
    };
  }

  for (const rule of RULES) {
    const hit = rule(head);
    if (!hit) continue;
    const host = input.url.hostname;
    const looksLikeTemplate = PREVIEW_HOST.test(host) && TEMPLATE_HOST.test(host);
    return {
      verdict: 'default-metadata',
      finding: {
        generator: hit.generator,
        fields: hit.fields,
        severity: looksLikeTemplate ? 'info' : 'warning',
      },
      reason: looksLikeTemplate
        ? `this looks like a published ${hit.generator} template, where shipping the default is correct`
        : `the HTML served to crawlers and link unfurlers still carries the ${hit.generator} scaffold default`,
    };
  }

  return { verdict: 'clean', finding: null, reason: 'the page sets its own title and description' };
}
